name: "Setup Chitrank Bot"
description: "Generates a GitHub App token for automated tasks"
inputs:
  client-id:
    description: "The GitHub App Client ID"
    required: true
  private-key:
    description: "The GitHub App Private Key"
    required: true
  permission-contents:
    description: "Repository contents permission for the generated token"
    required: true
  permission-issues:
    description: "Repository issues permission for the generated token"
    required: false
  permission-pull-requests:
    description: "Repository pull requests permission for the generated token"
    required: false
outputs:
  token:
    description: "The generated GitHub App token"
    value: ${{ steps.generate_token.outputs.token }}
runs:
  using: "composite"
  steps:
    - name: Create Bot Token 🤖🔑
      id: generate_token
      uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
      with:
        client-id: ${{ inputs.client-id }}
        private-key: ${{ inputs.private-key }}
        permission-contents: ${{ inputs.permission-contents }}
        permission-issues: ${{ inputs.permission-issues }}
        permission-pull-requests: ${{ inputs.permission-pull-requests }}
