import { execSync } from "node:child_process"
import { readFile, readdir, writeFile } from "node:fs/promises"
import path from "node:path"
import { fileURLToPath } from "node:url"

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)
const projectRoot = path.resolve(__dirname, "..")
const srcDir = path.join(projectRoot, "src")
const componentsDir = path.join(srcDir, "components")

async function fileExists(filePath) {
	try {
		await readFile(filePath)
		return true
	} catch {
		return false
	}
}

async function run() {
	// 1. Scan components
	const dirEntries = await readdir(componentsDir, { withFileTypes: true })
	const components = []

	for (const entry of dirEntries) {
		if (entry.isDirectory()) {
			const hasIndexTs = await fileExists(
				path.join(componentsDir, entry.name, "index.ts")
			)
			const hasIndexTsx = await fileExists(
				path.join(componentsDir, entry.name, "index.tsx")
			)
			if (hasIndexTs || hasIndexTsx) {
				components.push(entry.name)
			}
		}
	}
	components.sort()

	// 2. Scan foundations
	const foundationsDir = path.join(srcDir, "foundations")
	const foundationEntries = await readdir(foundationsDir, {
		withFileTypes: true,
	})
	const foundations = []
	for (const entry of foundationEntries) {
		if (
			entry.isFile() &&
			(entry.name.endsWith(".ts") || entry.name.endsWith(".tsx")) &&
			!entry.name.endsWith(".d.ts")
		) {
			foundations.push(entry.name.replace(/\.tsx?$/, ""))
		}
	}
	foundations.sort()

	// 3. Scan lib
	const libDir = path.join(srcDir, "lib")
	const libEntries = await readdir(libDir, { withFileTypes: true })
	const libs = []
	for (const entry of libEntries) {
		if (
			entry.isFile() &&
			(entry.name.endsWith(".ts") || entry.name.endsWith(".tsx")) &&
			!entry.name.endsWith(".d.ts")
		) {
			libs.push(entry.name.replace(/\.tsx?$/, ""))
		}
	}
	libs.sort()

	// 4. Generate src/index.ts
	const indexContentLines = [
		"// This file is auto-generated by scripts/sync-exports.mjs",
		"// Do not edit directly.",
		"",
	]
	for (const comp of components) {
		indexContentLines.push(`export * from "./components/${comp}"`)
	}
	for (const found of foundations) {
		indexContentLines.push(`export * from "./foundations/${found}"`)
	}
	for (const lib of libs) {
		indexContentLines.push(`export * from "./lib/${lib}"`)
	}
	indexContentLines.push("")

	const indexTsPath = path.join(srcDir, "index.ts")
	await writeFile(indexTsPath, indexContentLines.join("\n"), "utf8")
	console.log(`✓ Generated index.ts with ${components.length} components`)

	// 5. Update package.json.lib
	const pkgLibPath = path.join(projectRoot, "package.json.lib")
	const pkgLibRaw = await readFile(pkgLibPath, "utf8")
	const pkgLib = JSON.parse(pkgLibRaw)

	// Keep static/general exports
	const newExports = {
		".": {
			types: "./index.d.ts",
			import: "./index.js",
		},
	}

	// Add dynamic component-level exports
	for (const comp of components) {
		newExports[`./${comp}`] = {
			types: `./components/${comp}/index.d.ts`,
			import: `./components/${comp}/index.js`,
		}
	}

	// Add remaining wildcard and theme exports
	newExports["./components/*"] = {
		types: "./components/*/index.d.ts",
		import: "./components/*/index.js",
	}
	newExports["./foundations/*"] = {
		types: "./foundations/*.d.ts",
		import: "./foundations/*.js",
	}
	newExports["./lib/*"] = {
		types: "./lib/*.d.ts",
		import: "./lib/*.js",
	}
	newExports["./theme.css"] = {
		default: "./styles/theme.css",
	}
	newExports["./package.json"] = "./package.json"

	pkgLib.exports = newExports
	await writeFile(pkgLibPath, JSON.stringify(pkgLib, null, "\t") + "\n", "utf8")
	console.log(`✓ Updated package.json.lib exports`)

	// 6. Update tsconfig.json paths
	const tsconfigPath = path.join(projectRoot, "tsconfig.json")
	const tsconfigRaw = await readFile(tsconfigPath, "utf8")
	const tsconfig = JSON.parse(tsconfigRaw)

	const newPaths = {
		"@/*": ["./app/*"],
		"@chitrank2050/monoline-ui": ["./src/index.ts"],
	}

	// Dynamic component paths
	for (const comp of components) {
		newPaths[`@chitrank2050/monoline-ui/${comp}`] = [`./src/components/${comp}`]
	}

	// Dynamic foundations and lib paths
	newPaths["@chitrank2050/monoline-ui/*"] = ["./src/*"]

	tsconfig.compilerOptions.paths = newPaths
	await writeFile(
		tsconfigPath,
		JSON.stringify(tsconfig, null, "\t") + "\n",
		"utf8"
	)
	console.log(`✓ Updated tsconfig.json paths`)

	// 7. Output src/metadata.json
	const metadata = {
		count: components.length,
		components: components,
	}
	const metadataPath = path.join(srcDir, "metadata.json")
	await writeFile(
		metadataPath,
		JSON.stringify(metadata, null, "\t") + "\n",
		"utf8"
	)
	console.log(
		`✓ Generated src/metadata.json with component count: ${components.length}`
	)

	// 8. Format generated files
	try {
		const prettierBin = path.join(
			projectRoot,
			"node_modules",
			".bin",
			"prettier"
		)
		execSync(
			`"${prettierBin}" --write "${tsconfigPath}" "${metadataPath}" "${indexTsPath}"`,
			{
				cwd: projectRoot,
				stdio: "pipe",
			}
		)
		console.log(`✓ Formatted generated files with Prettier`)
	} catch {
		// Fallback silently if prettier fails
	}
}

run().catch((err) => {
	console.error(err)
	process.exit(1)
})
