import { execFile } from "node:child_process"
import { readFile, readdir, writeFile } from "node:fs/promises"
import path from "node:path"
import { fileURLToPath } from "node:url"
import { promisify } from "node:util"

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)
const projectRoot = path.resolve(__dirname, "..")
const execFileAsync = promisify(execFile)
const srcDir = path.join(projectRoot, "src")
const componentsDir = path.join(srcDir, "components")
const checkMode = process.argv.includes("--check")
const mismatches = []

async function fileExists(filePath) {
	try {
		await readFile(filePath)
		return true
	} catch {
		return false
	}
}

function generatedContentMatches(filePath, current, generated) {
	if (filePath.endsWith(".json") || filePath.endsWith(".json.lib")) {
		try {
			return (
				JSON.stringify(JSON.parse(current)) ===
				JSON.stringify(JSON.parse(generated))
			)
		} catch {
			return false
		}
	}

	return current === generated
}

async function writeGenerated(filePath, content, label) {
	if (checkMode) {
		let current
		try {
			current = await readFile(filePath, "utf8")
		} catch {
			mismatches.push(path.relative(projectRoot, filePath))
			return
		}
		if (!generatedContentMatches(filePath, current, content)) {
			mismatches.push(path.relative(projectRoot, filePath))
		}
		return
	}

	await writeFile(filePath, content, "utf8")
	console.log(label)
}

async function run() {
	// 1. Scan components
	const dirEntries = await readdir(componentsDir, { withFileTypes: true })
	const components = []

	for (const entry of dirEntries) {
		if (entry.isDirectory()) {
			const hasIndexTs = await fileExists(
				path.join(componentsDir, entry.name, "index.ts")
			)
			const hasIndexTsx = await fileExists(
				path.join(componentsDir, entry.name, "index.tsx")
			)
			if (hasIndexTs || hasIndexTsx) {
				components.push(entry.name)
			}
		}
	}
	components.sort()

	// 1b. Clean up CSS imports in component index.ts files for JSR compatibility,
	// and collect which components have CSS files.
	const componentsWithCss = []
	for (const comp of components) {
		const cssPath = path.join(componentsDir, comp, `${comp}.css`)
		if (await fileExists(cssPath)) {
			componentsWithCss.push(comp)
		}

		const indexTsPath = path.join(componentsDir, comp, "index.ts")
		if (await fileExists(indexTsPath)) {
			const content = await readFile(indexTsPath, "utf8")
			const cssImportRegex = new RegExp(
				`import\\s+["']\\./${comp}\\.css["'];?\\r?\\n?`,
				"g"
			)
			if (cssImportRegex.test(content)) {
				await writeGenerated(
					indexTsPath,
					content.replace(cssImportRegex, ""),
					`✓ Removed CSS import from ${comp}/index.ts`
				)
			}
		}
	}

	// 2. Scan foundations
	const foundationsDir = path.join(srcDir, "foundations")
	const foundationEntries = await readdir(foundationsDir, {
		withFileTypes: true,
	})
	const foundations = []
	for (const entry of foundationEntries) {
		if (
			entry.isFile() &&
			(entry.name.endsWith(".ts") || entry.name.endsWith(".tsx")) &&
			!entry.name.endsWith(".d.ts")
		) {
			foundations.push(entry.name.replace(/\.tsx?$/, ""))
		}
	}
	foundations.sort()

	// 3. Scan lib
	const libDir = path.join(srcDir, "lib")
	const libEntries = await readdir(libDir, { withFileTypes: true })
	const libs = []
	for (const entry of libEntries) {
		if (
			entry.isFile() &&
			(entry.name.endsWith(".ts") || entry.name.endsWith(".tsx")) &&
			!entry.name.endsWith(".d.ts")
		) {
			libs.push(entry.name.replace(/\.tsx?$/, ""))
		}
	}
	libs.sort()

	const indexContentLines = [
		"/**",
		" * @module",
		" * Main entry point for Monoline UI.",
		" */",
		"",
		"// This file is auto-generated by scripts/sync-exports.mjs",
		"// Do not edit directly.",
		"",
	]
	for (const comp of components) {
		indexContentLines.push(`export * from "./components/${comp}"`)
	}
	for (const found of foundations) {
		indexContentLines.push(`export * from "./foundations/${found}"`)
	}
	for (const lib of libs) {
		indexContentLines.push(`export * from "./lib/${lib}"`)
	}
	indexContentLines.push("")

	const indexTsPath = path.join(srcDir, "index.ts")
	await writeGenerated(
		indexTsPath,
		indexContentLines.join("\n"),
		`✓ Generated index.ts with ${components.length} components`
	)

	// 5. Update package.json.lib
	const pkgLibPath = path.join(projectRoot, "package.json.lib")
	const pkgLibRaw = await readFile(pkgLibPath, "utf8")
	const pkgLib = JSON.parse(pkgLibRaw)

	// Keep static/general exports
	const newExports = {
		".": {
			types: "./index.d.ts",
			import: "./index.js",
		},
	}

	// Add dynamic component-level exports
	for (const comp of components) {
		newExports[`./${comp}`] = {
			types: `./components/${comp}/index.d.ts`,
			import: `./components/${comp}/index.js`,
		}
	}

	// Add remaining wildcard and theme exports
	newExports["./components/*"] = {
		types: "./components/*/index.d.ts",
		import: "./components/*/index.js",
	}
	newExports["./foundations/*"] = {
		types: "./foundations/*.d.ts",
		import: "./foundations/*.js",
	}
	newExports["./lib/*"] = {
		types: "./lib/*.d.ts",
		import: "./lib/*.js",
	}
	newExports["./theme.css"] = {
		style: "./styles/theme.css",
		default: "./styles/theme.css",
	}
	newExports["./styles/theme.css"] = {
		style: "./styles/theme.css",
		default: "./styles/theme.css",
	}
	newExports["./package.json"] = "./package.json"

	pkgLib.exports = newExports
	await writeGenerated(
		pkgLibPath,
		JSON.stringify(pkgLib, null, "\t") + "\n",
		"✓ Updated package.json.lib exports"
	)

	// 5b. Update jsr.json exports
	const jsrPath = path.join(projectRoot, "jsr.json")
	const jsrRaw = await readFile(jsrPath, "utf8")
	const jsr = JSON.parse(jsrRaw)
	const jsrExports = {
		".": "./src/index.ts",
	}
	for (const comp of components) {
		jsrExports[`./${comp}`] = `./src/components/${comp}/index.ts`
	}
	jsr.exports = jsrExports
	await writeGenerated(
		jsrPath,
		JSON.stringify(jsr, null, "\t") + "\n",
		"✓ Updated jsr.json exports"
	)

	// 6. Update tsconfig.json paths
	const tsconfigPath = path.join(projectRoot, "tsconfig.json")
	const tsconfigRaw = await readFile(tsconfigPath, "utf8")
	const tsconfig = JSON.parse(tsconfigRaw)

	const newPaths = {
		"@/*": ["./app/*"],
		"@chitrank2050/monoline-ui": ["./src/index.ts"],
	}

	// Dynamic component paths
	for (const comp of components) {
		newPaths[`@chitrank2050/monoline-ui/${comp}`] = [`./src/components/${comp}`]
	}

	// Dynamic foundations and lib paths
	newPaths["@chitrank2050/monoline-ui/*"] = ["./src/*"]

	tsconfig.compilerOptions.paths = newPaths
	await writeGenerated(
		tsconfigPath,
		JSON.stringify(tsconfig, null, "\t") + "\n",
		"✓ Updated tsconfig.json paths"
	)

	const metadataPath = path.join(srcDir, "metadata.json")
	let existingSize = "12kb"
	try {
		const raw = await readFile(metadataPath, "utf8")
		const parsed = JSON.parse(raw)
		if (parsed.size) {
			existingSize = parsed.size
		}
	} catch {
		// Ignore if metadata.json does not exist yet
	}

	const metadata = {
		count: components.length,
		components: components,
		size: existingSize,
	}
	await writeGenerated(
		metadataPath,
		JSON.stringify(metadata, null, "\t") + "\n",
		`✓ Generated src/metadata.json with component count: ${components.length}`
	)

	// 7b. Update src/foundations/theme.css component style imports
	const themeCssPath = path.join(srcDir, "foundations", "theme.css")
	let themeCss = await readFile(themeCssPath, "utf8")
	const cssImports = componentsWithCss
		.map((comp) => `@import "../components/${comp}/${comp}.css";`)
		.join("\n")

	const startToken = "/* @components-start */"
	const endToken = "/* @components-end */"
	const startIndex = themeCss.indexOf(startToken)
	const endIndex = themeCss.indexOf(endToken)

	if (startIndex === -1 || endIndex === -1 || endIndex <= startIndex) {
		throw new Error("Could not find a valid components block in theme.css")
	}

	themeCss =
		themeCss.slice(0, startIndex + startToken.length) +
		"\n" +
		cssImports +
		"\n" +
		themeCss.slice(endIndex)

	await writeGenerated(
		themeCssPath,
		themeCss,
		`✓ Updated theme.css with ${componentsWithCss.length} component style imports`
	)

	if (checkMode) {
		if (mismatches.length > 0) {
			console.error("Generated export files are out of sync:")
			for (const file of mismatches) {
				console.error(`- ${file}`)
			}
			console.error("Run `pnpm run sync-exports` and commit the updates.")
			process.exit(1)
		}
		console.log(
			`✓ Generated export files are in sync with ${components.length} components`
		)
		return
	}

	// 8. Format generated files
	const prettierBin = path.join(projectRoot, "node_modules", ".bin", "prettier")
	await execFileAsync(
		prettierBin,
		["--write", tsconfigPath, metadataPath, indexTsPath, jsrPath],
		{ cwd: projectRoot }
	)
	await execFileAsync(
		prettierBin,
		["--write", "--parser", "json", pkgLibPath],
		{ cwd: projectRoot }
	)
	console.log(`✓ Formatted generated files with Prettier`)
}

run().catch((err) => {
	console.error(err)
	process.exit(1)
})
