name: Stale Issues Closer ⏰

on:
  schedule:
    - cron: "30 1 * * *" # Every day at 01:30 UTC

jobs:
  stale:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - name: Harden Runner 🛡️
        uses: step-security/harden-runner@a5ad31d6a139d249332a2605b85202e8c0b78450 # v2.19.1
        with:
          egress-policy: audit

      - uses: actions/stale@v9
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: "This issue is stale because it has been open 45 days with no activity."
          stale-pr-message: "This PR is stale because it has been open 45 days with no activity."
          days-before-stale: 45
          days-before-close: 7
